name: single_page_scrollable_website
description: A new Flutter project.

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  expandable_page_view: ^1.0.17
  flutter:
    sdk: flutter
  flutter_lorem: ^2.0.0
  flutter_web_plugins:
    sdk: flutter
  scrollable_positioned_list: ^0.2.2
  shared_preferences: ^2.0.15
  tuple: ^2.0.0
  url_strategy: ^0.2.0
dev_dependencies:
  flutter_lints: ^2.0.1
